name: Build Windows / MSVC / CMake
description: Build a Windows library with MS Visual Studio based on a CMake setup
author: TwinFan

inputs:                       
  libName:
    description: "Library's name, used as file name"
    required: true
  flags:
    description: "Flags to be passed to CMake"
    required: false

outputs:
  lib-file-name:
    description: Path to the resulting lib
    value: ${{ steps.return.outputs.lib-file-name }}

runs:
  using: "composite"
  steps:
  - name: Build
    shell: cmd
    run: ${{ github.action_path }}\build-win.cmd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" build-win "${{ inputs.flags }}"
  - name: Test for Target
    shell: bash
    env:
      TARGET_LIB: build-win/${{ inputs.libName }}.lib
    run: |
      if [[ ! -f "$TARGET_LIB" ]]; then
        echo Expected target build not found: "$TARGET_LIB"
        exit 1
      fi
  - name: Return Value
    id: return
    shell: bash
    env:
      TARGET_LIB: build-win/${{ inputs.libName }}.lib
    run: echo "lib-file-name=$(echo $TARGET_LIB)" >> $GITHUB_OUTPUT
