name: Build MacOS / CMake
description: Build a MacOS plugin based on a CMake setup
author: TwinFan

inputs:                       
  libName:
    description: "Library's name, used both as top-level folder name and as file name as required by X-Plane"
    required: true
  flags:
    description: "Flags to be passed to CMake"
    required: false

outputs:
  lib-file-name:
    description: Path to the resulting lib file
    value: ${{ steps.return.outputs.lib-file-name }}

runs:
  using: "composite"
  steps:
  - name: Install required libs
    shell: bash
    run: |
      brew install ninja
  - name: Prepare
    shell: bash
    run: |
      mkdir build-mac
  - name: CMake
    shell: bash
    run: |
      cd build-mac
      pwd
      cmake -G Ninja ${{ inputs.flags }} ..
  - name: Build
    shell: bash
    run: |
      cd build-mac
      pwd
      ninja
  - name: Test for and Zip Framework
    shell: bash
    env:
      TARGET_LIB: build-mac/${{ inputs.libName }}.framework
    run: |
      if [[ ! -d "$TARGET_LIB" ]]; then
        echo Expected target build not found: "$TARGET_LIB"
        exit 1
      fi
      cd build-mac
      zip -9ry ${{ inputs.libName }}.framework.zip ${{ inputs.libName }}.framework 
  - name: Return Value
    id: return
    shell: bash
    env:
      TARGET_ZIP: build-mac/${{ inputs.libName }}.framework.zip
    run: echo "lib-file-name=$(echo $TARGET_ZIP)" >> $GITHUB_OUTPUT
